persons = r'\b(Ryan Cohen|RC|DeepFuckingValue|DFV|Jensen Huang|Pat Gelsinger|Nancy Pelosi|Paul Pelosi|Michael Burry|Warren Buffett|Cathie Wood|Bill Ackman|Ray Dalio|Lisa Su|Jamie Dimon|Jeremy Grantham|Keith Gill|Roaring Kitty|Chamath|Cramer|Coke Rat|Portnoy|Vlad|Vlad Tenev|Elon|Elon Musk|Daddy Elon|Jerome Powell|JPow|J Pow|Pappa Jerome|Adam Aron|Gustavo Arnal|Charlie Munger|Jack Ma|Joe Biden|Sleepy Joe|Bill Gates|Billy Gates|Alex Karp|Hal Mintz|Mary Daly|Leon Cooperman|Raj Subramaniam|Herbert Diess|Nigel Green|Peter Beck|Boris Johnson|Liz Truss|Steven Cohen|Thomas Peterffy|Steve Citrus|Stephen Roach|Mike Mayo|Daniel Ives|Frederick|Sam Altman|Altman|Zuck|Mark Zuckerberg|Marjorie Taylor Greene|MTG|Ken Griffin|Kenny Griffin)\b'

brokers = r'\b(Robinhood|RH|Robbinghood|Robindhood|Fidelity|Interactive Brokers|IBKR|TD Ameritrade|AMTD|Thinkorswim|E\*TRADE|eTrade|Webull|Revolut|CashApp|Cash App|SoFi|Tastyworks|eToro|WealthSimple|Vanguard|Charles Schwab|Schwab|DeGiro|FreeTrade|Free Trade|Capital\.com|Saxo Bank|Saxo|AJ Bell|Scalable Capital|Nordnet|Hargreaves Lansdown|Swiss Quote|TradeRepublic|Trade Republic|DriveWealth|Hatch|Avenue|Stake|Public|Chase|Merrill Lynch|Morgan Stanley|Goldman Sachs|Credit Suisse|JPMorgan|Coinbase|Binance|FTX|BofA|Citi|JPM|Pepperstone|Linqto|Lightspeed)\b'

funds = r'\b(Melvin Capital|Melvin|Citron Research|Citron|Shitron|Point72|Citadel|BlackRock|Black Rock|Susquehanna|SIG|Dimensional|Senvest|MUST Asset Management|IG Group|IG|Bridgewater|Muddy Waters|Ark Invest|Sabby Management|Sabby|Mott Capital Management|Sixth Street Partners|Archegos|Hindenburg Research|Hindenburg|Renaissance|RenTech|Icahn Enterprises|IEP)\b'

media = r'\b(Washington Post|Bloomberg News|Bloomberg|Reuters|CNBC|Investopedia|MarketWatch|Yahoo Finance|Yahoo|Dow Jones|The Street\.com|USA Today|New York Times|NYT|Barron\'s|Gannett|S3 Partners|S3|Forbes|Wall Street Journal|WSJ|Stocktwits|Twitter|Reddit|TikTok|YouTube|Facebook|Instagram|CNN|FT|Seeking Alpha|ZeroHedge|Benzinga|Finviz|Substack|Fox Business|MarketScreener|LunarCrush)\b'

tickers = r'\$?\b(GME|AMC|BB|NOK|SLV|ARKG|IPOC|BABA|TSLA|SNDL|AMZN|RKT|PLTR|MAC|GS2C|RBLX|ZOM|CLOV|BBBY|KOSS|NAKD|EXPR|VT|OTGLY|SPCE|BYND|AMD|APHA|NIO|AAPL|GOOGL|GOOG|MSFT|NVDA|META|NFLX|SNAP|PYPL|SQ|SHOP|PTON|LCID|RIVN|HOOD|SPY|SPX|SPXU|QQQ|SQQQ|TQQQ|VIX|SOXL|IWM|DIA|SOFI|MU|INTC|TSM|ASML|SNOW|MRVL|CDNS|SNPS|MSTR|SMCI|ARM|LLY|NVO|IBIT|BITO|COIN|RUM|NKE|GCT|RKLB|DKNG|WISH|HKD|DNUT|SAVE)\b'

companies = r'\b(GameStop|Gamestop|Nokia|BlackBerry|Blackberry|Microsoft|Walmart|Ferrari|Chipotle|Blockbuster|Netflix|Disney\+|Disney|Amazon|Apple|Tesla|GlobalFoundries|Google|Alphabet|Nvidia|Meta|Intel|Target|Costco|Macy\'s|Best Buy|Starbucks|Nike|Ford|Boeing|Palantir|Roblox|Zoom|Peloton|Unity|Snowflake|Crowdstrike|Desktop Metal|General Electric|General Motors|GM|GE|Supermicro|Broadcom|Eli Lilly|Novo Nordisk|OpenAI|Anthropic|Bed Bath & Beyond|FedEx|UPS|Micron Technologies|Micron|Western Digital|Volkswagen|BMW|Rivian|Lucid|Cineworld|Regal|Six Flags|Dollar Tree|Big Lots|Krispy Kreme|Beyond Meat|Spirit Airlines)\b'